name: Deploy to S3

on:
  push:
    branches:
      - main  # adjust this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
    
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        
    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://imad-terraform-bucket/ --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
