name: Deploy to S3

on:
  push:
    branches:
      - main  # adjust this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
    
    # - name: Install AWS CLI using python pip
    #   run: |
    #      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #      unzip awscliv2.zip
    #      sudo ./aws/install
    - name: Install AWS CLI v2
      run:  |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

    - name : verify aws cli
      run: aws --version

    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://imad-terraform-bucket/ --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  


